// Mozilla User Preferences

// DO NOT EDIT THIS FILE.
//
// If you make changes to this file while the application is running,
// the changes will be overwritten when the application exits.
//
// To change a preference value, you can either:
// - modify it via the UI (e.g. via about:config in the browser); or
// - set it within a user.js file in your profile.

user_pref("app.normandy.first_run", false);
user_pref("app.normandy.startupRolloutPrefs.layout.display-list.retain", true);
user_pref("app.normandy.startupRolloutPrefs.security.tls.version.fallback-limit", 4);
user_pref("app.normandy.user_id", "31c9d641-ac19-4bd5-8b39-ebf00a5b2ed1");
user_pref("app.update.lastUpdateTime.addon-background-update-timer", 1549679898);
user_pref("app.update.lastUpdateTime.blocklist-background-update-timer", 1549680018);
user_pref("app.update.lastUpdateTime.browser-cleanup-thumbnails", 1549679538);
user_pref("app.update.lastUpdateTime.recipe-client-addon-run", 1549679778);
user_pref("app.update.lastUpdateTime.search-engine-update-timer", 1549679658);
user_pref("app.update.lastUpdateTime.telemetry_modules_ping", 1549680258);
user_pref("app.update.lastUpdateTime.xpi-signature-verification", 1549680138);
user_pref("browser.bookmarks.restore_default_bookmarks", false);
user_pref("browser.cache.disk.capacity", 358400);
user_pref("browser.cache.disk.filesystem_reported", 1);
user_pref("browser.cache.disk.smart_size.first_run", false);
user_pref("browser.laterrun.bookkeeping.profileCreationTime", 1549704567);
user_pref("browser.laterrun.bookkeeping.sessionCount", 3);
user_pref("browser.laterrun.enabled", true);
user_pref("browser.migration.version", 68);
user_pref("browser.newtabpage.activity-stream.impressionId", "{e2c77d2c-e116-46b6-a73b-e7f76399215f}");
user_pref("browser.newtabpage.activity-stream.migrationLastShownDate", 1549645200);
user_pref("browser.newtabpage.activity-stream.migrationRemainingDays", 3);
user_pref("browser.newtabpage.storageVersion", 1);
user_pref("browser.onboarding.notification.last-time-of-changing-tour-sec", 1549704674);
user_pref("browser.onboarding.seen-tourset-version", 2);
user_pref("browser.onboarding.tour-type", "new");
user_pref("browser.pageActions.persistedActions", "{\"version\":1,\"ids\":[\"bookmark\",\"bookmarkSeparator\",\"copyURL\",\"emailLink\",\"addSearchEngine\",\"sendToDevice\",\"pocket\",\"screenshots\"],\"idsInUrlbar\":[\"pocket\",\"bookmark\"]}");
user_pref("browser.pagethumbnails.storage_version", 3);
user_pref("browser.places.smartBookmarksVersion", 8);
user_pref("browser.safebrowsing.provider.google4.lastupdatetime", "1549681270881");
user_pref("browser.safebrowsing.provider.google4.nextupdatetime", "1549683097881");
user_pref("browser.safebrowsing.provider.mozilla.lastupdatetime", "1549681127914");
user_pref("browser.safebrowsing.provider.mozilla.nextupdatetime", "1549684727914");
user_pref("browser.search.countryCode", "ID");
user_pref("browser.search.region", "ID");
user_pref("browser.sessionstore.upgradeBackup.latestBuildID", "20180704192505");
user_pref("browser.slowStartup.averageTime", 9952);
user_pref("browser.slowStartup.samples", 3);
user_pref("browser.startup.homepage_override.buildID", "20180704192505");
user_pref("browser.startup.homepage_override.mstone", "61.0.1");
user_pref("browser.uiCustomization.state", "{\"placements\":{\"widget-overflow-fixed-list\":[],\"PersonalToolbar\":[\"personal-bookmarks\"],\"nav-bar\":[\"back-button\",\"forward-button\",\"stop-reload-button\",\"home-button\",\"customizableui-special-spring1\",\"urlbar-container\",\"customizableui-special-spring2\",\"downloads-button\",\"library-button\",\"sidebar-button\"],\"toolbar-menubar\":[\"menubar-items\"],\"TabsToolbar\":[\"tabbrowser-tabs\",\"new-tab-button\",\"alltabs-button\"]},\"seen\":[\"developer-button\"],\"dirtyAreaCache\":[\"PersonalToolbar\",\"nav-bar\",\"toolbar-menubar\",\"TabsToolbar\"],\"currentVersion\":14,\"newElementCount\":2}");
user_pref("browser.urlbar.placeholderName", "Google");
user_pref("browser.urlbar.timesBeforeHidingSuggestionsHint", 0);
user_pref("datareporting.policy.dataSubmissionPolicyAcceptedVersion", 2);
user_pref("datareporting.policy.dataSubmissionPolicyNotifiedTime", "1549704575367");
user_pref("devtools.onboarding.telemetry.logged", true);
user_pref("distribution.canonical.bookmarksProcessed", true);
user_pref("distribution.iniFile.exists.appversion", "61.0.1");
user_pref("distribution.iniFile.exists.value", true);
user_pref("extensions.blocklist.lastModified", "Fri, 08 Feb 2019 12:03:20 GMT");
user_pref("extensions.blocklist.pingCountTotal", 2);
user_pref("extensions.blocklist.pingCountVersion", 2);
user_pref("extensions.databaseSchema", 26);
user_pref("extensions.getAddons.cache.lastUpdate", 1549679899);
user_pref("extensions.getAddons.databaseSchema", 5);
user_pref("extensions.lastAppBuildId", "20180704192505");
user_pref("extensions.lastAppVersion", "61.0.1");
user_pref("extensions.lastPlatformVersion", "61.0.1");
user_pref("extensions.pendingOperations", false);
user_pref("extensions.systemAddonSet", "{\"schema\":1,\"addons\":{}}");
user_pref("extensions.webextensions.uuids", "{\"webcompat@mozilla.org\":\"ed832df7-cc3d-4289-9f1c-0e708d124fb2\",\"screenshots@mozilla.org\":\"b5003fd2-c8b4-412b-aa86-67c07f0020b5\"}");
user_pref("lightweightThemes.usedThemes", "[]");
user_pref("media.gmp-manager.buildID", "20180704192505");
user_pref("media.gmp-manager.lastCheck", 1549704632);
user_pref("media.gmp.storage.version.observed", 1);
user_pref("network.cookie.prefsMigrated", true);
user_pref("network.predictor.cleaned-up", true);
user_pref("pdfjs.enabledCache.initialized", true);
user_pref("pdfjs.enabledCache.state", true);
user_pref("pdfjs.migrationVersion", 2);
user_pref("pdfjs.previousHandler.alwaysAskBeforeHandling", true);
user_pref("pdfjs.previousHandler.preferredAction", 4);
user_pref("places.history.expiration.transient_current_max_pages", 96171);
user_pref("plugin.disable_full_page_plugin_for_types", "application/pdf");
user_pref("privacy.sanitize.pending", "[{\"id\":\"newtab-container\",\"itemsToClear\":[],\"options\":{}}]");
user_pref("security.sandbox.content.tempDirSuffix", "b246abd3-09a9-4e6f-bdf9-7c982590d564");
user_pref("services.blocklist.addons.checked", 1549679981);
user_pref("services.blocklist.gfx.checked", 1549679981);
user_pref("services.blocklist.onecrl.checked", 1549679981);
user_pref("services.blocklist.pinning.checked", 1549679981);
user_pref("services.blocklist.plugins.checked", 1549679981);
user_pref("services.settings.clock_skew_seconds", 37);
user_pref("services.settings.last_etag", "\"1549649719840\"");
user_pref("services.settings.last_update_seconds", 1549679981);
user_pref("signon.importedFromSqlite", true);
user_pref("toolkit.startup.last_success", 1549681181);
user_pref("toolkit.telemetry.cachedClientID", "e3990a17-622e-401b-9279-861796f8b953");
user_pref("toolkit.telemetry.previousBuildID", "20180704192505");
user_pref("toolkit.telemetry.reportingpolicy.firstRun", false);
